### token
POST http://localhost:7001/api/v1/auth/token
content-type: application/json

{
  "username": "one",
  "password": "two"
}

### get user
GET http://localhost:7001/api/v1/users/me
Authorization: Bearer gw72w042GSFA_jQPU5a_orcG

### update user
PATCH http://localhost:7001/api/v1/users/me
content-type: application/json

{
  "teamName": "JS"
}

### token EMPTY
GET http://localhost:7001/api/v1/auth/token-info?token=gw72w042GSFA_jQPU5-yppHR

### sign up
POST http://localhost:7001/api/v1/users
content-type: application/json

{
  "username": "one",
  "password": "tw1o"
}

### create team
POST http://localhost:7001/api/v1/teams
content-type: application/json

{
  "name": "other"
}

### creaate character
POST http://localhost:7001/api/v1/characters
content-type: application/json

{
  "name": "alibaba",
  "userId": "6169b22b1ba9bbfbf503b8d9",
  "ownerUserId": "6169b22b1ba9bbfbf503b8d9"
}

### get my character
GET http://localhost:7001/api/v1/characters/me
content-type: application/json



### get teams
GET http://localhost:7001/api/v1/teams
content-type: application/json


### none
POST http://localhost:7001/22222
content-type: application/json

{
  "username": "one",
  "passowrd": "tw1o"
}