### token
POST http://localhost:7001/api/v1/auth/token
content-type: application/json

{
  "username": "one",
  "password": "two"
}

### get user
GET http://localhost:7001/api/v1/users/me
Authorization: Bearer gw72w042GSFA_jQPU5a_orcG


### token EMPTY
GET http://localhost:7001/api/v1/auth/token?token

### sign up
POST http://localhost:7001/api/v1/users
content-type: application/json

{
  "username": "one",
  "password": "tw1o"
}

### none
POST http://localhost:7001/22222
content-type: application/json

{
  "username": "one",
  "passowrd": "tw1o"
}